import Head from "next/head";
import { client } from "../../libs/client";
import Link from "next/link";

export default function Home({ blog }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="">
                <div className="max-w-3xl my-20 mx-auto bg-white p-10">
                    <h1 className=" py-2 text-xl font-bold border-b-2 pb-2">
                        サイトに関するご連絡に関して。
                    </h1>
                    <p className="mt-10">
                        サイトに関してのご連絡は下記までお願い致します。
                    </p>
                    <p>原則5営業日までに返信いたします。</p>
                    <p className="text-center mt-10">
                        <a href="mailto:yossii20001021@gmail.com">
                            yossii20001021@gmail.com
                        </a>
                    </p>
                </div>
            </main>
        </>
    );
}

// データをテンプレートに受け渡す部分の処理
export const getStaticProps = async () => {
    const data = await client.get({ endpoint: "blogs" });

    return {
        props: {
            blog: data.contents,
        },
    };
};
