import Head from "next/head";
import { client } from "../libs/client";
import Link from "next/link";
import Image from "next/image";
import { AuthorRecommend } from "../components/AuthorRecommend";

export default function Home({ blog }) {
    return (
        <>
            <Head>
                <title>KAKKOEASY</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className="max-w-3xl my-20 mx-auto">
                    <AuthorRecommend blog={blog} />
                    <div className="rounded-lg mt-10">
                        <h2 className="py-2 text-center text-2xl font-bold border-b-2 pb-2 ">
                            記事一覧
                        </h2>
                        <ul className="mt-10 grid grid-cols-2 gap-x-5 gap-y-10 ">
                            {blog.map((blog) => (
                                <div
                                    key={blog.id}
                                    className="bg-white rounded-lg shadow-xl"
                                >
                                    <li>
                                        <Link
                                            href={`/blog/${blog.id}`}
                                            className="w-full"
                                        >
                                            <div className="">
                                                <Image
                                                    className="w-full aspect-video object-cover rounded-t-lg"
                                                    src={
                                                        blog.eyecatch?.url
                                                            ? blog.eyecatch?.url
                                                            : "https://placehold.jp/300x250.png?dammy"
                                                    }
                                                    alt=""
                                                    width="300"
                                                    height="200"
                                                />
                                            </div>
                                            <p className="font-bold px-3 pt-3 pb-5">
                                                {blog.title}
                                            </p>
                                        </Link>
                                    </li>
                                </div>
                            ))}
                        </ul>
                        <div className="text-center mt-10">
                            <Link
                                className="inline-block px-6 py-4 text-md font-bold text-white bg-black border rounded-lg"
                                href="/blog/"
                            >
                                記事一覧を見る
                            </Link>
                        </div>
                    </div>
                </div>
            </main>
        </>
    );
}

// データをテンプレートに受け渡す部分の処理
export const getStaticProps = async () => {
    const data = await client.get({ endpoint: "blogs" });

    return {
        props: {
            blog: data.contents,
        },
    };
};
